# Generated by Django 4.1.3 on 2022-11-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('ticker', models.CharField(max_length=30)),
                ('datePurchased', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=10)),
                ('costBasis', models.DecimalField(decimal_places=10, max_digits=10)),
                ('buyType', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
