# Generated by Django 4.1.3 on 2022-11-18 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portfolio',
            new_name='portfolioModel',
        ),
    ]
